[workspace]
resolver = "2"

members = [
    "sshoxy", "sshoxy-bin", "sshoxy-haas",
]

default-members = [
	"sshoxy",
]

# Binary size optimizations
[profile.release]
codegen-units = 1
strip = true
lto = true
opt-level = "z"
