[package]
name = "sshoxy"
version = "0.2.2"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0"
log = "0"
russh = { version = "0.52.1", features = ["async-trait"]}
tokio = { version = "1", features = ["macros", "net", "io-util"] }

[dev-dependencies]
env_logger = "0"
